### ISSUE TITLE
MOQ is wrong

### ISSUE THREAD

**Issue by SheraByte** [codersaiful/woo-min-max-quantity-step-control-single#12]
when set the minimum quantity to 10, it asks to order 11. if so the minimum is 11. Also a message display as order minimum of 10.

**Comment by mdibrahimk48** [comment]
Can you please give us more details? Like some screenshots or product page links.
Thanks

**Comment by mdibrahimk48** [comment]
Hello,

I wanted to check in and see if you have managed to resolve the issue you were facing. If not, please don't hesitate to let me know. I'm here to assist you and provide any further support you may need.

Thank you for your time and cooperation.
