### ISSUE TITLE
Constantly having to activate license

### ISSUE THREAD

**Issue by HeydenSupply** [codersaiful/woo-min-max-quantity-step-control-single#13]
My license key needs activation almost daily to keep up with updates.  Sometimes I get the message more than once per day.

**Comment by mdibrahimk48** [comment]
Hello @HeydenSupply ,

Our technical team solve the license issue on the Min-Max Step Quantity Pro plugin.
Please download it (updated version) and check it from your site.

Regards,
CodeAstrology Team
