### ISSUE TITLE
License activation issue

### ISSUE THREAD

**Issue by pmferro** [codersaiful/woo-min-max-quantity-step-control-single#14]
I constantly get a "Please activate Min Max Quantity & Step Control for WooCommerce license to get automatic updates" 
I enter the license get the OK message and then the next day again, all the time

**Comment by mdibrahimk48** [comment]
Hello @pmferro,

Our technical team solve the license issue on the Min-Max Step Quantity Pro plugin.
Please download it (updated version) and check it from your site.

Regards,
CodeAstrology Team
