### ISSUE TITLE
Plugin blocks submission of post.php on order edit page when product quantity is changed below minimum quantity by admin

### ISSUE THREAD

**Issue by jankohoener** [codersaiful/woo-min-max-quantity-step-control-single#17]
Hello,

on our e-commerce store we recently had a case where after changing the product quantity on the order edit page manually (from minimum quantity 25 to 12) the Order Actions and other buttons using the post.php form were not submitted anymore. I verified this behavior only happens when the quantity is changed by admin below the minimum quantity not when it's above minimum quantity. It's also not a plugin/theme conflict as this remains when only Twenty Twenty Three, Woocommerce and Min Max Quantity & Step Control for WooCommerce are enabled.

There are cases in our business where we allow customers to order below our usual minimum quantity. But by default they shouldn't be able to order below minimum quantity, only when approved by admin. That's why it should be possible for admin to reduce below minimum quantity and still keep everything as usual.

Here's how to reproduce the issue:

- wcmmq default settings and Order Page (Condition) turned off
- create product with minimum quantity 25
- create order for this product
- change quantity by admin to 12
- then try to do one of the Order Actions; it will not submit to post.php as it usually does and thus do as it says

**Comment by codersaiful** [comment]
Thanks for inform us. For now, u can disable a option:Order Page Condition.

See https://codeastrology.com/min-max-quantity/set-conditions-on-woocommerce-order-page/

Actually we set it for order page. Forgot to check for edit page. 
Check and let me know

**Comment by jankohoener** [comment]
It's disabled on our site already

**Comment by mdibrahimk48** [comment]
**Hello,**

Our technical team solve this issue. You can check it now by using the updated plugin version.

**The updated plugin link:** https://github.com/codersaiful/woo-min-max-quantity-step-control-single/tree/4.3.0

**Follow this helper doc for download:** https://wooproducttable.com/docs/doc/basic-tips/download-and-install-latest-version-plugin-from-github/

Regards,
**@mdibrahimk48** 
Technical Support Engineer, **CodeAstrology**
