### ISSUE TITLE
WooCommerce order actions no longer working after changing quantity on order edit page to below minimum quantity

### ISSUE THREAD

**Issue by jankohoener** [codersaiful/woo-min-max-quantity-step-control-single#19]
In our shop, when using the minimum quantity for a product but then changing the quantity to below minimum quantity on the order edit page and saving, the possible actions under "Order Actions" no longer work. I did a plugin conflict test and the bug disappeared when deacting this plugin.

To reproduce the bug, the following steps are necessary:

- WooCommerce store with this plugin installed and "Order Page (Condition)" deactivated
- one product with a minimum quantity > 1
- make one order containing that product with minimum quantity
- in the admin area change the quantity of the product to below minimum quantity and save
- now trying to do one of the "Order Actions" no longer works, that means, post.php is no longer submitted

Staging site with such a case is available in a confidential forum.

**Comment by mdibrahimk48** [comment]
Hello **@jankohoener,**

We are already solving this bug and deploying a feature in our plugin for control Order Page (Condition) control. 

**Please follow this helper documentation:** https://codeastrology.com/min-max-quantity/set-conditions-on-woocommerce-order-page/?ref=56

If you activate the option "Order Page (Condition)" - you can edit/change the order page with any quantity and save it. The order action also works with enable this button.

Thanks!

**Warmest Regards,**
Ibrahim
Technical Support Engineer, **CodeAstrology**
