### ISSUE TITLE
Quantity input should have up-down-arrows

### ISSUE THREAD

**Issue by jankohoener** [codersaiful/woo-min-max-quantity-step-control-single#20]
Hello,

currently the input field uses the <input type="text">. However that means that no up-down arrows are shown. They're part of <input type="number">

They would be very helpful for our users, especially when there are unusual quantity steps, e.g. we have some articles with 50, 100, 200 or 500 as steps, example: https://www.maxsel.de/produkt/k2-2004112-heco-topix-plus-holzschraube-8-x-100/

Warm regards,

Janko

**Comment by mdibrahimk48** [comment]
Hello,

I hope everything is working fine. I am closing this issue. If you need more help, you can create a new one.

If you have any questions or need further assistance, please do not hesitate to reach out to us. We are here to provide you with the best support possible.

Thank you for choosing our plugin.
