### ISSUE TITLE
Certificate verification disabled

### ISSUE THREAD

**Issue by klajn1911** [codersaiful/woo-min-max-quantity-step-control-single#26]
Dear Team,
while monitoring performance, we have noticed some SSL errors caused by the plugin. It looks like license validity check is not passed. At the same time our license status page is ok. 

The process takes 1,5s of page load time and moreover check license validity call is initiated with every WP/Woo admin view load, so it is visibly affecting performance. 

Would you please review this topic? Let me know if you need any further info.

![image-20231013-094155](https://github.com/codersaiful/woo-min-max-quantity-step-control-single/assets/135129248/af6ee3ed-52de-479c-86a0-c738b68c9239)

WP v 6.3.1
Woo 7.9.0

**Comment by fazlebarisn** [comment]
Which plugin version you are using?

**Comment by klajn1911** [comment]
Thanks for your reply.
This is 5.6 + 2.0.8 for Pro

**Comment by mdibrahimk48** [comment]
We won't enable SSL verification. It doesn't work on many sites after updates. Enabling SSL verification may lead to issues.

Hope you understand! 

Best regards,
