### ISSUE TITLE
New Feature request

### ISSUE THREAD

**Issue by SollerComp** [codersaiful/woo-min-max-quantity-step-control-single#4]
We would love to have this new feature:  Allow the dimension of a product to change based on the product quantity.
Let me explain why:  We sell 50"  fabrics.  If someone buys 2 yards, the width is obviously 50", but if they buy 1 yard, we can turn the fabric the width way and the product width is 36" (36" widex50"long ). A 50"+ box costs a lot more to ship than a 42" box.  Currently, there is no way to calc the correct shipping without having 2 products (one for 1yard and one for 2+yards).   This is very sloppy.  We are happy to pay for this feature.  Please help.  jon@sollercomposites.com

We have your pro version of the software....

**Comment by fazlebarisn** [comment]
Hello,
Thank you for reaching out. 
I do not clearly understand your requirement. Can  You please explain more? Also, you can create a ticket on our support site.
https://codeastrology.com/support/
If possible, please record a video, that's how we can understand better. 
Share your site link as well. 
Regards
Fazle Bari

**Comment by mdibrahimk48** [comment]
Hello,

I wanted to check in and see if you have managed to resolve the issue you were facing. If not, please don't hesitate to let me know. I'm here to assist you and provide any further support you may need.

Thank you for your time and cooperation.
