### ISSUE TITLE
Add a [quantity_step] placeholder to the Step validation error message

### ISSUE THREAD

**Issue by jankohoener** [codersaiful/woo-min-max-quantity-step-control-single#5]
Currently in the Step validation error message, the only placeholders are [should_min] and [should_next]. However, I find the message not very helpful, because nowhere does it get clear for the customer that a product has to be bought in steps of [quantity_step]. Rather than using the default message, I'd rather use a message like "This product can only be bought in steps of [quantity_step]. The nearest valid values are [should_min] and [should_next]."
But that placeholder isn't available yet and I'd be glad to have it.

**Comment by fazlebarisn** [comment]
Thanks for your suggestion, we will add quantity_step placeholders.

**Comment by codersaiful** [comment]
Dear @jankohoener, Thanks for your suggestion, I will add this feature right now. I am just working right now.

**Comment by codersaiful** [comment]
![image](https://user-images.githubusercontent.com/6463919/195328848-346b687f-3a40-4af6-9170-4f6935113a38.png)

Finally done and added more Shortcode for Message for all Message.
Such for Step Variation Message: Available shortcode [should_min],[should_next],[product_name],[variation_name],[quantity],[min_quantity],[step_quantity]
