### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by JawaherKhawjah** [codersaiful/woo-min-max-quantity-step-control-single#8]
Can you make this feature work with auction-type products in woocommerce?
I look forward to your reply, thank you

**Comment by fazlebarisn** [comment]
If the product has a quality box, it should work. Can you please give us more details? Like some screenshots or product page links.
Thanks

**Comment by mdibrahimk48** [comment]
Hello,

I wanted to check in and see if you have managed to resolve the issue you were facing. If not, please don't hesitate to let me know. I'm here to assist you and provide any further support you may need.

Thank you for your time and cooperation.
